In [1]:
#라이브러리 임포트(한 곳에서 하는 것이 좋음)

import numpy as np
import pandas as pd
import matplotlib

In [25]:
data=np.loadtxt("data/movies/ratings.dat",delimiter="::",dtype=np.int64) 
# int64 = 8byte 정수(long형)

In [10]:
data[:5,:] # 처음 5행의 데이터만 확인

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [11]:
data.shape # 데이터 형태 확인 (행,열)

(1000209, 4)

In [12]:
mean_rating_total=data[:,2].mean()
mean_rating_total

3.581564453029317

In [26]:
user_ids=np.unique(data[:,0]) 
# 모든 행의 1번째 값인 id 값(인덱스가 1인 경우 두 번째 값인 영화 제목 값을 얻을 수 있음)
print(user_ids[:5])
print(user_ids.shape) # 6040 개의 unique한 user_ids 찾음

[1 2 3 4 5]
(6040,)


In [15]:
mean_values=[]

for user_id in user_ids:
    data_for_user=data[data[:,0]==user_id,:] # 해당하는 user_id에 대한 값만 가져옴
    # data[:,0]==user_id 전체 데이터에서 각 행의 1열인 user_id만 모두 골라줌
    # : 열은 전체를 다 가져옴 -> 같은 user_id인 값 전체를 가져옴
    value=data_for_user[:,2].mean() # 평점 정보의 평균
    mean_values.append([user_id, value]) # 한 명의 user_id별 전체 평점 평균

In [16]:
mean_values[:10]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606]]

In [20]:
mean_array=np.array(mean_values,dtype=np.float32)
print(mean_array[:5])
print(mean_array.shape) #행 6040, 열 2개인 배열 생성 완료

[[1.        4.188679 ]
 [2.        3.7131784]
 [3.        3.9019608]
 [4.        4.1904764]
 [5.        3.1464646]]
(6040, 2)


In [23]:
np.savetxt("data/movies/userid_result.csv",mean_array,fmt="%.2f", delimiter=",")

In [34]:
movie_ids=np.unique(data[:,1])

mean_values=[]

for movie_id in movie_ids:
    data_for_movie=data[data[:,1]==movie_id,:]
    value=data_for_movie[:,2].mean()
    mean_values.append([movie_id, value])
    
movie_mean_array=np.array(mean_values,dtype=np.float32)

print(mean_values[:10])
print(movie_mean_array[:5])
print(movie_mean_array.shape)

np.savetxt("data/movies/movieid_result.csv",movie_mean_array,fmt="%.2f",delimiter=",")

[[1, 4.146846413095811], [2, 3.20114122681883], [3, 3.01673640167364], [4, 2.7294117647058824], [5, 3.0067567567567566], [6, 3.8787234042553194], [7, 3.410480349344978], [8, 3.014705882352941], [9, 2.656862745098039], [10, 3.5405405405405403]]
[[1.        4.1468463]
 [2.        3.201141 ]
 [3.        3.0167365]
 [4.        2.7294118]
 [5.        3.0067568]]
(3706, 2)
