# Linear Regression

In [1]:
import numpy as np

x_data = np.array([1,2,3,4,5]).reshape(5,1)
t_data = np.array([2,3,4,5,6]).reshape(5,1)

#raw_data = [[1,2],[2,3],[3,4],[4,5],[5,6]]
#Y=X+1

print("x_data.shape =", x_data.shape, "t_data.shape =", t_data.shape)

x_data.shape = (5, 1) t_data.shape = (5, 1)


In [2]:
W=np.random.rand(1,1) #2차원배열
b=np.random.rand(1)
print("W= ",W,", W.shape = ", W.shape, "b= ",b,", b.shape = ", b.shape)

W=  [[0.44214605]] , W.shape =  (1, 1) b=  [0.50792443] , b.shape =  (1,)


In [3]:
def loss_func(x,t):
    y=np.dot(x,W)+b
    
    return(np.sum((t-y)**2)/(len(x)))

In [4]:
def numerical_derivative(f,x):
    delta_x= 1e-4
    grad=np.zeros_like(x) 
    # 수치미분 결과를 grad에 저장
    # x와 똑같은 shape을 가진 배열(혹은 행렬) 생성 (요소값은 0임)
    
    it=np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
    #모든 입력변수에 대해 편미분하기 위해 iterator 획득
    # iterator 하나 생성. 플래그는 멀티 인덱스 설정
    # 멀티 인덱스를 설정하면 다차원 배열이라도 
    # 순차적으로 interator 생성 후 값을 꺼낼 수 있음
    
    while not it.finished:
        idx=it.multi_index
        
        tmp_val=x[idx] 
        # 임시 변수로 x[idx] 의 원값을 저장
        # numpy 타입은 mutable 이므로 원래 값 보관
        
        x[idx]=float(tmp_val)+delta_x # 전향 차분
        fx1=f(x) #f(x+delta_x) # 첫번째 인자로 들어온 함수를 대입
        
        x[idx]=tmp_val-delta_x # 후향 차분
        fx2=f(x) #f(x-delta_x) # 첫번째 인자로 들어온 함수를 다시 대입
        
        grad[idx]=(fx1-fx2)/(2*delta_x) # 미분 결과를 grad에...
        
        x[idx]=tmp_val
        it.iternext()
        
    return grad

In [5]:
# 손실함수 값 계산 함수
# 입력변수 x, t : numpy type
def error_val(x,t):
    y=np.dot(x,W)+b
    
    return(np.sum((t-y)**2)/(len(x)))

In [6]:
# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
# 입력변수 x : numpy type
def predict(x):
    y=np.dot(x,W)+b
    
    return y

In [7]:
learning_rate = 1e-2 # 발산하는 경우, 1e-3 ~ 1e-6 등으로 바꾸어서 실행

f=lambda x: loss_func(x_data, t_data)

print("Initial error value = ", error_val(x_data,t_data), "Initial W = ", W, "\n", ", b = ", b)

for step in range(8001):
    W -= learning_rate * numerical_derivative(f,W)
    
    b -= learning_rate * numerical_derivative(f,b)
    
    if(step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data,t_data), "W = ", W, ", b = ", b)

Initial error value =  5.3123874604369 Initial W =  [[0.44214605]] 
 , b =  [0.50792443]
step =  0 error value =  3.1336540288247376 W =  [[0.59439845]] , b =  [0.54210204]
step =  400 error value =  0.0014173174846548774 W =  [[1.02444727]] , b =  [0.91175921]
step =  800 error value =  9.043323466344874e-05 W =  [[1.00617534]] , b =  [0.97771053]
step =  1200 error value =  5.770175010355223e-06 W =  [[1.00155988]] , b =  [0.99436972]
step =  1600 error value =  3.681712787782914e-07 W =  [[1.00039402]] , b =  [0.9985778]
step =  2000 error value =  2.3491504204557577e-08 W =  [[1.00009953]] , b =  [0.99964075]
step =  2400 error value =  1.4988968493804216e-09 W =  [[1.00002514]] , b =  [0.99990926]
step =  2800 error value =  9.563848042595962e-11 W =  [[1.00000635]] , b =  [0.99997708]
step =  3200 error value =  6.102300463685043e-12 W =  [[1.0000016]] , b =  [0.99999421]
step =  3600 error value =  3.8936284638853045e-13 W =  [[1.00000041]] , b =  [0.99999854]
step =  4000 error

In [8]:
predict(10)

array([[11.]])

# Multi-variable regression
### example

In [27]:
import numpy as np

loaded_data=np.loadtxt('data/data-01-test-score.csv', delimiter=',',dtype=np.float32)

print(loaded_data)
x_data=loaded_data[:,0:-1]
t_data=loaded_data[:,[-1]]

#데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape)

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]
x_data.ndim =  2 , x_data.shape =  (25, 3)
t_data.ndim =  2 , t_data.shape =  (25, 1)


In [28]:
W=np.random.rand(3,1) # 3X1 행렬
b=np.random.rand(1)
print("W = ", W, ", W.shape = ", W.shape, ", b =", b, ", b.shape = ", b.shape)

W =  [[0.45625837]
 [0.58824675]
 [0.45249258]] , W.shape =  (3, 1) , b = [0.20734241] , b.shape =  (1,)


In [29]:
def loss_func(x,t):
    y=np.dot(x,W)+b
    
    return(np.sum((t-y)**2)/(len(x)))

In [30]:
def numerical_derivative(f,x):
    delta_x= 1e-4
    grad=np.zeros_like(x) 
    # 수치미분 결과를 grad에 저장
    # x와 똑같은 shape을 가진 배열(혹은 행렬) 생성 (요소값은 0임)
    
    it=np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
    #모든 입력변수에 대해 편미분하기 위해 iterator 획득
    # iterator 하나 생성. 플래그는 멀티 인덱스 설정
    # 멀티 인덱스를 설정하면 다차원 배열이라도 
    # 순차적으로 interator 생성 후 값을 꺼낼 수 있음
    
    while not it.finished:
        idx=it.multi_index
        
        tmp_val=x[idx] 
        # 임시 변수로 x[idx] 의 원값을 저장
        # numpy 타입은 mutable 이므로 원래 값 보관
        
        x[idx]=float(tmp_val)+delta_x # 전향 차분
        fx1=f(x) #f(x+delta_x) # 첫번째 인자로 들어온 함수를 대입
        
        x[idx]=tmp_val-delta_x # 후향 차분
        fx2=f(x) #f(x-delta_x) # 첫번째 인자로 들어온 함수를 다시 대입
        
        grad[idx]=(fx1-fx2)/(2*delta_x) # 미분 결과를 grad에...
        
        x[idx]=tmp_val
        it.iternext()
        
    return grad

In [31]:
def error_val(x,t):
    y=np.dot(x,W)+b
    
    return(np.sum((t-y)**2)/(len(x)))

In [32]:
def predict(x):
    y=np.dot(x,W)+b
    
    return y

In [33]:
learning_rate = 1e-5 # 발산하는 경우, 1e-3 ~ 1e-6 등으로 바꾸어서 실행

f=lambda x: loss_func(x_data, t_data)

print("Initial error value = ", error_val(x_data,t_data), "Initial W = ", W, "\n", ", b = ", b)

for step in range(40001):
    W -= learning_rate * numerical_derivative(f,W)
    
    b -= learning_rate * numerical_derivative(f,b)
    
    if(step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data,t_data), "W = ", W, ", b = ", b)

Initial error value =  1827.45102105688 Initial W =  [[0.45625837]
 [0.58824675]
 [0.45249258]] 
 , b =  [0.20734241]
step =  0 error value =  684.1891634123369 W =  [[0.52424299]
 [0.65654902]
 [0.52271786]] , b =  [0.20785486]
step =  400 error value =  11.44245590498413 W =  [[0.60228802]
 [0.71570859]
 [0.7040618 ]] , b =  [0.20849359]
step =  800 error value =  9.968174570267127 W =  [[0.57761088]
 [0.67722224]
 [0.76565653]] , b =  [0.20825748]
step =  1200 error value =  8.9144848027519 W =  [[0.55548455]
 [0.64578587]
 [0.81788374]] , b =  [0.20795407]
step =  1600 error value =  8.159238280336705 W =  [[0.53563325]
 [0.62017672]
 [0.86220623]] , b =  [0.20759353]
step =  2000 error value =  7.616169617367773 W =  [[0.51781281]
 [0.59937831]
 [0.89985451]] , b =  [0.20718447]
step =  2400 error value =  7.2242789063913095 W =  [[0.50180681]
 [0.58254615]
 [0.93186404]] , b =  [0.20673415]
step =  2800 error value =  6.940369961482612 W =  [[0.48742322]
 [0.5689791 ]
 [0.9591065

In [34]:
test_data=np.array([100,98,81])

predict(test_data)

array([178.86221976])