# 머신러닝 분석 개요
### 머신러닝 수학

- 수치미분

In [4]:
def my_func1(x):
    return x**2+x+1

In [2]:
def numerical_derivative(f,x):
    delta_x=1e-4 #0.0001으로 변화량의 크기(델타) (극한 대신 아주 작은 수로 대체)
    return (f(x+delta_x)-f(x-delta_x))/(2*delta_x)

In [5]:
result=numerical_derivative(my_func1,3)
print(result)

7.000000000010331


In [7]:
import numpy as np

def my_func2(x):
    return 3*x*(np.exp(x))

In [8]:
def numerical_derivative(f,x):
    delta_x=1e-4 #0.0001
    return (f(x+delta_x)-f(x-delta_x))/(2*delta_x)

In [9]:
result=numerical_derivative(my_func2,2)
print(result)

66.50150507518049


- 수치미분 - 다변수

In [25]:
# while 문으로 모든 x값을 수식에 대입
# 모든 변수를 포함하고 있는 numpy 객체(배열, 행렬)

def numerical_derivative(f,x):
    delta_x= 1e-4
    grad=np.zeros_like(x) 
    # 수치미분 결과를 grad에 저장
    # x와 똑같은 shape을 가진 배열(혹은 행렬) 생성 (요소값은 0임)
    
    print("debug 1. initial input variable =", x)
    print("debug 2. initial grad =", grad)
    print("========================================")
    
    it=np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
    #모든 입력변수에 대해 편미분하기 위해 iterator 획득
    # iterator 하나 생성. 플래그는 멀티 인덱스 설정
    # 멀티 인덱스를 설정하면 다차원 배열이라도 
    # 순차적으로 interator 생성 후 값을 꺼낼 수 있음
    
    while not it.finished:
        idx=it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] =", x[idx])
        
        tmp_val=x[idx] 
        # 임시 변수로 x[idx] 의 원값을 저장
        # numpy 타입은 mutable 이므로 원래 값 보관
        
        x[idx]=float(tmp_val)+delta_x # 전향 차분
        fx1=f(x) #f(x+delta_x) # 첫번째 인자로 들어온 함수를 대입
        
        x[idx]=tmp_val-delta_x # 후향 차분
        fx2=f(x) #f(x-delta_x) # 첫번째 인자로 들어온 함수를 다시 대입
        
        grad[idx]=(fx1-fx2)/(2*delta_x) # 미분 결과를 grad에...
        
        print("debug 4. grad[idx] =", grad[idx])
        print("debug 5. grad =", grad)
        
        x[idx]=tmp_val
        it.iternext()
        
    return grad

In [19]:
# 입력 변수 1 개인 함수 f(x)=x**2
def func1(input_obj):
    x=input_obj[0]
    return x**2

# x=3.0 에서의 편미분 값
numerical_derivative(func1, np.array([3.0]))

debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx =  (0,) , x[idx] = 3.0
debug 4. grad[idx] = 6.000000000012662
debug 5. grad = [6.]


array([6.])

In [24]:
# 입력 변수 2 개인 함수 f(x,y)=2x+3xy+y^3
def func1(input_obj):
    x=input_obj[0]
    y=input_obj[1]
    
    return (2*x + 3*x*y + np.power(y,3))

# (x,y)=(1.0,2.0) 에서의 편미분 값
input = np.array([1.0,2.0])

numerical_derivative(func1, input)

debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx =  (0,) , x[idx] = 1.0
debug 4. grad[idx] = 7.999999999990237
debug 5. grad = [8. 0.]
debug 3. idx =  (1,) , x[idx] = 2.0
debug 4. grad[idx] = 15.000000010019221
debug 5. grad = [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [28]:
# 입력 변수 4 개인 함수
# f(w,x,y,z)=wx+wyz+3w+zy^2
# input_obj는 행렬

def func1(input_obj):
    
    w=input_obj[0,0]
    x=input_obj[0,1]
    y=input_obj[1,0]
    z=input_obj[1,1]
    
    return (w*x + x*y*z + 3*w + z*np.power(y,2))

# 입력을 2X2 행렬로 구성함
input = np.array([[1.0, 2.0],[3.0, 4.0]])

numerical_derivative(func1, input)

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx =  (0, 0) , x[idx] = 1.0
debug 4. grad[idx] = 5.000000000023874
debug 5. grad = [[5. 0.]
 [0. 0.]]
debug 3. idx =  (0, 1) , x[idx] = 2.0
debug 4. grad[idx] = 13.00000000000523
debug 5. grad = [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx =  (1, 0) , x[idx] = 3.0
debug 4. grad[idx] = 32.00000000006753
debug 5. grad = [[ 5. 13.]
 [32.  0.]]
debug 3. idx =  (1, 1) , x[idx] = 4.0
debug 4. grad[idx] = 15.000000000000568
debug 5. grad = [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])